speedtest.schedule.enabled=false
speedtest.schedule.cron=0 * * * * ?
speedtest.config.url=https://www.speedtest.net/speedtest-config.php
speedtest.server.base-uri[0]=https://www.speedtest.net/speedtest-servers-static.php
speedtest.server.base-uri[1]=https://c.speedtest.net/speedtest-servers-static.php
speedtest.server.base-uri[2]=https://www.speedtest.net/speedtest-servers.php
speedtest.server.base-uri[3]=https://c.speedtest.net/speedtest-servers.php
speedtest.server.limit=10
speedtest.latency.tests-per-server=3
speedtest.http.use-caches=false
speedtest.http.user-agent=speedtest-client
speedtest.http.connection=Keep-Alive
speedtest.http.cache-control=no-cache
speedtest.http.download.max-buffer-size=10240
speedtest.http.upload.max-buffer-size=10240
speedtest.http.upload.referer=https://c.speedtest.net/flash/speedtest.swf
speedtest.http.upload.content-type=application/x-www-form-urlencoded
speedtest.transfer.download.sizes[0]=350
speedtest.transfer.download.sizes[1]=500
speedtest.transfer.download.sizes[2]=750
speedtest.transfer.download.sizes[3]=1000
speedtest.transfer.download.sizes[4]=1500
speedtest.transfer.download.sizes[5]=2000
speedtest.transfer.download.sizes[6]=2500
speedtest.transfer.download.sizes[7]=3000
speedtest.transfer.download.sizes[8]=3500
speedtest.transfer.download.sizes[9]=4000
speedtest.transfer.download.thread-factor=2
speedtest.transfer.upload.sizes[0]=32768
speedtest.transfer.upload.sizes[1]=65536
speedtest.transfer.upload.sizes[2]=131072
speedtest.transfer.upload.sizes[3]=262144
speedtest.transfer.upload.sizes[4]=524288
speedtest.transfer.upload.sizes[5]=1048576
speedtest.transfer.upload.sizes[6]=7340032
speedtest.transfer.upload.thread-factor=4
speedtest.csv.file=target/csv/results.csv
speedtest.csv.charset=UTF-8
speedtest.csv.delimiter=;
speedtest.csv.row-separator=\n
speedtest.share.url=https://www.speedtest.net/api/api.php
speedtest.image.path=target/share/
speedtest.image.buffer-size=2048
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
quarkus.log.file.enabled=true
quarkus.log.file.path=target/logs/quarkus.log
quarkus.log.file.format=${quarkus.log.console.format}
quarkus.console.color=true
quarkus.banner.path=banner.txt
quarkus.http.port=9000
